name: Node.js CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Генерируем lock-файл если отсутствует
          if [ ! -f package-lock.json ]; then
            npm install --package-lock
          else
            npm ci
          fi

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cat-tournament:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Deploy container
        run: |
          docker run -d -p 3000:3000 \
          ${{ secrets.DOCKER_USERNAME }}/cat-tournament:latest
